
[[language]]
name = "python"
auto-format = true
language-servers = [
    {name = "pyright"},
    {name = "ruff-lsp"},
]
roots = ["uv.lock", ".git", "pyproject.toml"]
file-types = ["py", "ipynb"]
formatter = { command = "bash", args = ["-c", "uvx ruff check --fix - | uvx ruff format -"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}


