inherits = "ayu_evolve"
"ui.background" ={}
# "ui.statusline.normal" = { fg = "black", bg = "orange", modifiers = ["bold"] }
# "ui.statusline.insert" = { fg = "black", bg = "green", modifiers = ["bold"] }
# "ui.statusline.select" = { fg = "black", bg = "magenta", modifiers = ["bold"] }
# "ui.statusline" = { fg = "black", bg = "blue"}
